<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="chatbot" nsURI="http://www.rm2pt.com/chatbot" nsPrefix="chatbot">
  <eClassifiers xsi:type="ecore:EClass" name="Admin"/>
  <eClassifiers xsi:type="ecore:EClass" name="User" abstract="true" eSuperTypes="#//Admin #//NormalUser">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="chat" upperBound="-1" eType="#//Chat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="normals" eType="#//User"
        eOpposite="#//User/usereOpposite"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usereOpposite" upperBound="-1"
        eType="#//User" eOpposite="#//User/normals"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Chat">
    <eStructuralFeatures xsi:type="ecore:EReference" name="message" upperBound="-1"
        eType="#//Message" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Message">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NormalUser"/>
</ecore:EPackage>
